// Imports
import { useState } from 'react'

// Components
import SideNav from '../components/SideNav/SideNav'

import Head from 'next/head'

export default function Home() {

  const [sideNavActive, setSideNavActive] = useState(true)

  return (
    <div>
      <Head>
        <title>ProjMatch</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <main>
        <SideNav isActive={sideNavActive} />
      </main>
    </div>
  )
}
