// Imports
import { useState } from 'react'

// Components
import SideNav from '../components/SideNav/SideNav'

import Head from 'next/head'
import Link from 'next/link'

export default function Home() {

  return (
    <div className='w-full h-full'>
      <Head>
        <title>ProjMatch</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <main className='w-full h-full flex flex-row'>
        <div className='grow'>
          <SideNav /> 
        </div>
        <div className='flex h-full shrink items-center'>
          <div className='post-alignment'>
            <h1><Link href="/Landing/Landing">go to landing</Link></h1>
          </div>
        </div>
      </main>
    </div>
  )
}
